### ISSUE TITLE
TypeError: undefined is not an object when using transforms

### ISSUE THREAD

**Issue by geoffharcourt** [zmbush/coffeelint-ruby#32]
I'm experiencing a problem where I can run `coffeelint` from npm (verison 1.9.1) and I'm able to use the  transforms feature, which converts some files to coffeescript prior to linting, but when I do it with `coffeelint.rb` at the command line or through a Rake task (using the bundled coffeelint 1.9.1 code), I get this error:

```shell
$ coffeelint.rb -f config/coffeelint.json app/assets/javascripts/components/page.coffee.cjsx

lint@(execjs):281:29: TypeError: undefined is not an object (evaluating 'ruleLoader.require') (ExecJS::ProgramError)
        from (execjs):2786:12
        from (execjs):2790:21
        from (execjs):1:46
        from global code@(execjs):1:58
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/execjs-2.4.0/lib/execjs/external_runtime.rb:32:in `exec'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/execjs-2.4.0/lib/execjs/external_runtime.rb:21:in `eval'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/execjs-2.4.0/lib/execjs/external_runtime.rb:39:in `call'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/lib/coffeelint.rb:49:in `lint'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/lib/coffeelint.rb:53:in `lint_file'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/lib/coffeelint.rb:104:in `run_test'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/lib/coffeelint/cmd.rb:86:in `block in main'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/lib/coffeelint/cmd.rb:82:in `each'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/lib/coffeelint/cmd.rb:82:in `main'
        from /Users/geoff/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/coffeelint-1.9.1/bin/coffeelint.rb:5:in `<top (required)>'
        from /Users/geoff/.rbenv/versions/2.2.1/bin/coffeelint.rb:23:in `load'
        from /Users/geoff/.rbenv/versions/2.2.1/bin/coffeelint.rb:23:in `<main>'
```

I get a similar issue if I specify the coffeelint.js file installed through npm, but I don't get the issue if I run my tests through the coffeelint executable that comes from npm. I'm trying to figure out if there's either something straightforward that I'm missing or if there's a way to allow the gem to use coffeelint with other npm packages to integrate transforms.

**Comment by zmbush** [comment]
If you can replicate this using the npm package, then this seems like an issue for coffeelint itself.
